name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AZURE_WEBAPP_PROD_NAME: software-testing-app
  AZURE_WEBAPP_DEV_NAME: software-testing-app-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build

    - name:  Changing version of the project
      run: |
          current_version=$(grep 'application.version' src/main/resources/application.properties | cut -d'=' -f2)
          new_version=$((current_version + 1))
          sed -i "s/project.version=$current_version/project.version=$new_version/" src/main/resources/application.properties
          echo "New version of project: $new_version"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/main/resources/application.properties
          git commit -m "Increment application version"
          git push
        
    - name: Testing with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: test

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3.1.3
      with:
        name: software-testing-app
        path: '${{ github.workspace }}/build/libs/software-methodology-testing-0.0.1-SNAPSHOT.jar'

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: software-testing-app

      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_DEV_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
          package: '*.jar'
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: software-testing-app

      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
          package: '*.jar'
